---
- name: Install and start Apache httpd
  hosts: intranet

  tasks:
    - name: httpd and firewalld package is present
      yum:
        name: 
          - httpd
          - firewalld
        state: latest

    - name: correct index.html is present
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true

    - name: firewalld is started
      service:
        name: firewalld
        state: started
        enabled: true

    - name: firewalld permits httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

- name: Test the web server
  hosts: localhost
  become: no

  tasks:
    - name: connect to intranet web server
      uri:
        url: http://worker2.appcluster.net
        status_code: 200

